#!/bin/bash
./oss 2> /dev/null
mn -c
if [ -z $1 ];
then
  remote_ip='127.0.0.1'
else
  remote_ip=$1
fi
mn --custom bb.py --topo bb --mac --controller=remote,ip=$remote_ip,port=6653 --switch ovs,protocols=OpenFlow13
